name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Github Action"
      uses: actions/checkout@v4

    - name: "Login to Github Container Registry"
      uses: docker/login-action@v3
      with:
        registry: ${{secrets.REGISTRY_URL}}
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ./trump-tracker-api
        file: ./trump-tracker-api/Dockerfile
        push: true
        tags: ${{secrets.REGISTRY_USERNAME}}/trump_tracker_api:latest
